name: 3dgs_pa
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - plyfile=0.8.1
  - python=3.8.3
  - pip=22.3.1
  - pytorch=1.13.1
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - tqdm
  - pip:
    - pypose
    - submodules/diff-gaussian-rasterization-pp_lie_pose_adjust
    - git+https://github.com/camenduru/simple-knn.git